compressionLevel: mixed

enableGlobalCache: false

httpProxy: "${http_proxy:-}"

httpsProxy: "${http_proxy:-}"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.com/"
