packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - e-virt-table@1.4.1 || 1.4.5
  - brace-expansion@2.0.3 || 5.0.5 || 5.0.6
  - yaml@2.8.3
  - lodash-es@4.17.24
  - postcss@8.5.10
  - uuid@11.1.1
  - esbuild@0.28.1
  - vite@8.0.16
  - '@babel/core@7.29.1'
  - js-yaml@4.1.2
