packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
overrides:
  'brace-expansion@^2.0.1': 2.1.2
  'brace-expansion@^5.0.0': 5.0.7
  fast-uri: 3.1.5
minimumReleaseAgeExclude:
  - e-virt-table
  - brace-expansion@2.1.2 || 5.0.7
  - fast-uri@3.1.5
  - yaml@2.8.3
  - lodash-es@4.17.24
  - postcss@8.5.10
  - uuid@11.1.1
  - esbuild@0.28.1
  - vite@8.0.16
  - '@babel/core@7.29.1'
  - js-yaml@4.1.2
